<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiNet.HashSimilarityTK.Core\DiNet.HashSimilarityTK.Core.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.FileProcessing.Core\DiNet.HashSimilarityTK.FileProcessing.Core.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.FileProcessing.Infrastructure\DiNet.HashSimilarityTK.FileProcessing.Infrastructure.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.Infrastructure\DiNet.HashSimilarityTK.Infrastructure.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.MetricsEngine.Application\DiNet.HashSimilarityTK.MetricsEngine.Application.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.MetricsEngine.Infrastructure\DiNet.HashSimilarityTK.MetricsEngine.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestRoot\TextSample1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TextSample1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
