<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	  <PackAsTool>true</PackAsTool>
	  <ToolCommandName>hsim</ToolCommandName>
	  <PackageOutputPath>./nupkg</PackageOutputPath>

	  <Version>0.1.1</Version>
	  <Description>CLI tool for detecting similar files using HashSimilarityTK</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <Authors>DifolderyXXL</Authors>
	  <PackageTags>similarity;hash;cli;tool</PackageTags>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
	  
    <PackageReference Include="Ignore" Version="0.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiNet.HashSimilarityTK.CliToolkit\DiNet.HashSimilarityTK.CliToolkit.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.FileProcessing.Core\DiNet.HashSimilarityTK.FileProcessing.Core.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.FileProcessing.Infrastructure\DiNet.HashSimilarityTK.FileProcessing.Infrastructure.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.Infrastructure\DiNet.HashSimilarityTK.Infrastructure.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.MetricsEngine.Application\DiNet.HashSimilarityTK.MetricsEngine.Application.csproj" />
    <ProjectReference Include="..\DiNet.HashSimilarityTK.MetricsEngine.Infrastructure\DiNet.HashSimilarityTK.MetricsEngine.Infrastructure.csproj" />
  </ItemGroup>
</Project>